package com.owenlarosa.popularmovies.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.owenlarosa.popularmovies.db.Movie;
import com.owenlarosa.popularmovies.db.Review;
import com.owenlarosa.popularmovies.db.Trailer;

import com.owenlarosa.popularmovies.db.MovieDao;
import com.owenlarosa.popularmovies.db.ReviewDao;
import com.owenlarosa.popularmovies.db.TrailerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig movieDaoConfig;
    private final DaoConfig reviewDaoConfig;
    private final DaoConfig trailerDaoConfig;

    private final MovieDao movieDao;
    private final ReviewDao reviewDao;
    private final TrailerDao trailerDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        movieDaoConfig = daoConfigMap.get(MovieDao.class).clone();
        movieDaoConfig.initIdentityScope(type);

        reviewDaoConfig = daoConfigMap.get(ReviewDao.class).clone();
        reviewDaoConfig.initIdentityScope(type);

        trailerDaoConfig = daoConfigMap.get(TrailerDao.class).clone();
        trailerDaoConfig.initIdentityScope(type);

        movieDao = new MovieDao(movieDaoConfig, this);
        reviewDao = new ReviewDao(reviewDaoConfig, this);
        trailerDao = new TrailerDao(trailerDaoConfig, this);

        registerDao(Movie.class, movieDao);
        registerDao(Review.class, reviewDao);
        registerDao(Trailer.class, trailerDao);
    }
    
    public void clear() {
        movieDaoConfig.getIdentityScope().clear();
        reviewDaoConfig.getIdentityScope().clear();
        trailerDaoConfig.getIdentityScope().clear();
    }

    public MovieDao getMovieDao() {
        return movieDao;
    }

    public ReviewDao getReviewDao() {
        return reviewDao;
    }

    public TrailerDao getTrailerDao() {
        return trailerDao;
    }

}
