package com.owenlarosa.popularmovies.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRAILER".
 */
public class Trailer {

    private Long id;
    private String identifier;
    private String key;
    private String name;

    public Trailer() {
    }

    public Trailer(Long id) {
        this.id = id;
    }

    public Trailer(Long id, String identifier, String key, String name) {
        this.id = id;
        this.identifier = identifier;
        this.key = key;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdentifier() {
        return identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
