package com.owenlarosa.popularmovies.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.io.Serializable;

/**
 * Entity mapped to table "TRAILER".
 */
public class Trailer implements Serializable {

    private Long id;
    private String identifier;
    private String key;
    private String name;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Trailer() {
    }

    public Trailer(Long id) {
        this.id = id;
    }

    public Trailer(Long id, String identifier, String key, String name) {
        this.id = id;
        this.identifier = identifier;
        this.key = key;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdentifier() {
        return identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
